version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - webnet

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - webnet

networks:
  webnet:
